# Generated by Django 5.0.1 on 2024-01-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.FloatField(max_length=5000)),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.FloatField(max_length=50)),
            ],
        ),
    ]
